### ISSUE TITLE
gatherURLs.py

### ISSUE THREAD

**Issue by Pythonc0de** [its0x08/IPTV-tool#1]
python gatherURLs.py dorkList.txt 
[i] Found 86 in total.
[*] Hunting URLs for Admin panel
[i] 0 of them are alive!

in urls.txt nothing store

**Comment by its0x08** [comment]
Since they are local desktop using noip to have a reverse ip they turn them down so i means the pc is not on and u cannot connect .. 
The results are scrapped from search engines so the dont update their status in real time..

**Comment by Pythonc0de** [comment]
I like this Script but need more work bro 
add me 6cyFPbGgNZ5L8rT0Abs9NuykVzdhBA44 FERON-74

**Comment by its0x08** [comment]
Im open to ideas ...
