### ISSUE TITLE
部分链接采集不到频道

### ISSUE THREAD

**Issue by liuqq58** [its0x08/IPTV-tool#8]
https://iptv-org.github.io/iptv/countries/cn.m3u
比如以上无法采集
https://raw.githubusercontent.com/Rivens7/Livelist/main/CCTV.m3u
这种又可以采集   
第一种可以浏览器打开就直接下载了，第二种浏览器打开是打开一个网页页面
希望可以优化下

**Comment by its0x08** [comment]
Non English comments are not accepted!
